version: "3.6"
services:

  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "7022:22"
      - "7080:80"
      - "7443:443"
    volumes:
      - gitlab_stack_data:/var/opt/gitlab
      - gitlab_stack_logs:/var/log/gitlab
      - gitlab_stack_config:/etc/gitlab
    shm_size: '256m'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://structam.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 7022
    configs:
    - source: gitlab_config
      target: /omnibus_config.rb

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 1

configs:
  gitlab_config:
    external: True

secrets:
  gitlab_root_password:
    external: True

volumes:
  gitlab_stack_data:
  gitlab_stack_logs:
  gitlab_stack_config: