version: "3.6"
services:

  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "7022:22"
      - "7080:80"
      - "7443:443"
      - "8989:8989"
    volumes:
      - gitlab_stack_data:/var/opt/gitlab
      - gitlab_stack_logs:/var/log/gitlab
      - gitlab_stack_config:/etc/gitlab
    shm_size: '256m'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://structam.com:8989'
        gitlab_rails['initial_root_password'] = $GITLAB_ROOT_PASSWORD
        gitlab_rails['gitlab_shell_ssh_port'] = 7022
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
    constraints:
      - node.labels.main_gitlab_server == true

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 1

configs:
  gitlab:
    file: ./gitlab.rb

secrets:
  gitlab_root_password:
    file: ./root_password.txt

volumes:
  gitlab_stack_data:
  gitlab_stack_logs:
  gitlab_stack_config: